const {
  NODE_PORT,
  NODE_DB_URL,
  NODE_UPLOAD_IMAGE_SFTP_HOST,
  NODE_UPLOAD_IMAGE_SFTP_PORT,
  NODE_UPLOAD_IMAGE_SFTP_USERNAME,
  NODE_UPLOAD_IMAGE_SFTP_PRIVATEKEY,
  NODE_UPLOAD_IMAGE_DIRNAME,
  NODE_UPLOAD_IMAGE_URL
} = process.env

module.exports = {
  PORT: NODE_PORT,
  DB_URL: NODE_DB_URL,
  UPLOAD_IMAGE: {
    SFTP: {
      HOST: NODE_UPLOAD_IMAGE_SFTP_HOST,
      PORT: NODE_UPLOAD_IMAGE_SFTP_PORT,
      USERNAME: NODE_UPLOAD_IMAGE_SFTP_USERNAME,
      PRIVATEKEY: NODE_UPLOAD_IMAGE_SFTP_PRIVATEKEY
    },
    DIRNAME: NODE_UPLOAD_IMAGE_DIRNAME,
    URL: NODE_UPLOAD_IMAGE_URL
  }
}
