// require process.env
const {
  NODE_PORT,
  NODE_DB_URL,
  NODE_UPLOAD_IMAGE_SFTP_HOST,
  NODE_UPLOAD_IMAGE_SFTP_PORT,
  NODE_UPLOAD_IMAGE_SFTP_USERNAME,
  NODE_UPLOAD_IMAGE_SFTP_PRIVATEKEY,
  NODE_UPLOAD_IMAGE_DESTINATION,
  NODE_UPLOAD_IMAGE_URL
} = process.env

module.exports = {
  PORT: NODE_PORT,
  DB_URL: NODE_DB_URL,
  UPLOAD_IMAGE: {
    STORAGE: {
      sftp: {
        host: NODE_UPLOAD_IMAGE_SFTP_HOST,
        port: NODE_UPLOAD_IMAGE_SFTP_PORT,
        username: NODE_UPLOAD_IMAGE_SFTP_USERNAME,
        privateKey: NODE_UPLOAD_IMAGE_SFTP_PRIVATEKEY
      },
      destination: NODE_UPLOAD_IMAGE_DESTINATION
    },
    URL: NODE_UPLOAD_IMAGE_URL
  }
}
